on: [push]
name: Test
env:
  MY_NAME: testUser
jobs:
  webrequest_test:
    runs-on: ubuntu-latest
    name: Get Time Issue Reopened
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node for testing
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      # - run: npm test
      - name: post-request output
        shell: pwsh
        run: |
          $output = '${{ steps.post-request.outputs.output }}' | ConvertFrom-Json
          Write-Host "Time from output $($output.time) statusCode $($output.statusCode)"
          $output.statusCode -eq 200
      - name: GET request
        id: get-request
        uses: dangcuong125/get-time-reopend-issue@main
        with:
          url: https://api.github.com/repos/bilisoftware/traphaco-manage/issues/133/timeline
          headers: '{"Authorization": "token ${{ secrets.TOKEN }}"}'
      - name: get-request output
        shell: pwsh
        run: |
          $output = '${{ steps.get-request.outputs.output }}'
